=== warework/sdk-java/warework-java-mod-core-ext/src/main/resources/META-INF/xsd/scope.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
	Warework Scope XML schema.
	
	@author Jose Schiaffino
	@version 3.0.0  
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="scope" type="Scope"/>

	<xsd:complexType name="Scope">	
		<xsd:sequence>
			<xsd:element name="parameters" type="Parameters" minOccurs="0" maxOccurs="1"  />						
			<xsd:element name="providers" type="Providers" minOccurs="0" maxOccurs="1" />
			<xsd:element name="objects" type="Objects" minOccurs="0" maxOccurs="1" />
			<xsd:element name="services" type="Services" minOccurs="0" maxOccurs="1" />
			<xsd:element name="context" type="Context" minOccurs="0" maxOccurs="1" />							
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="optional" />
		<xsd:attribute name="parent" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="Parameters">	
		<xsd:sequence>
			<xsd:element name="parameter" type="Parameter" maxOccurs="unbounded" minOccurs="0" />
		</xsd:sequence>	
	</xsd:complexType>	
	
	<xsd:complexType name="Parameter">	
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="required"/>			
	</xsd:complexType>		

	<xsd:complexType name="Providers">	
		<xsd:sequence>
			<xsd:element name="provider" type="Provider" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>	
	</xsd:complexType>	

	<xsd:complexType name="Provider">	
		<xsd:sequence>
			<xsd:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>	
		<xsd:attribute name="name" type="xsd:string" use="required"/>					
		<xsd:attribute name="class" type="xsd:string" use="required"/>
		<xsd:attribute name="scope" type="xsd:string" use="optional" default="system"/>
	</xsd:complexType>	

	<xsd:complexType name="Objects">	
		<xsd:sequence>
			<xsd:element name="object" type="ObjectReference" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>	
	</xsd:complexType>	
	
	<xsd:complexType name="ObjectReference">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="provider" type="xsd:string" use="required"/>
		<xsd:attribute name="object" type="xsd:string" use="required"/>	
		<xsd:attribute name="scope" type="xsd:string" use="optional" default="system"/>		
	</xsd:complexType>	
	
	<xsd:complexType name="Services">	
		<xsd:sequence>
			<xsd:element name="service" type="Service" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>	
	</xsd:complexType>	

	<xsd:complexType name="Service">	
		<xsd:sequence>
			<xsd:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>	
		<xsd:attribute name="name" type="xsd:string" use="required"/>					
		<xsd:attribute name="class" type="xsd:string" use="required"/>
		<xsd:attribute name="scope" type="xsd:string" use="optional" default="system"/>
	</xsd:complexType>
	
	<xsd:complexType name="Context">	
		<xsd:sequence>
			<xsd:element name="scope" type="Scope" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>	
	</xsd:complexType>	
	
</xsd:schema>

=== warework/sdk-java/warework-java-boot-loader-se/src/test/resources/META-INF/warework-java-boot-loader-se/system-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<scope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/scope.xsd">

	<parameters>
		<parameter name="name" value="john"/>
		<parameter name="color" value="red"/>					
	</parameters>	
	
	<providers>	
	
		<provider name="singleton-provider" class="com.warework.provider.SingletonProvider" />
		
		<provider name="standard-provider" class="com.warework.provider.StandardProvider">
			<parameter name="load-objects" value="false" />
			<parameter name="default-set" value="java.util.HashSet" />
			<parameter name="default-map" value="java.util.HashMap" />
			<parameter name="default-list" value="java.util.ArrayList" />
			<parameter name="string-builder" value="java.lang.StringBuilder" />
		</provider>		
		
	</providers>

	<objects>
		<object name="string-builder" provider="standard-provider" object="string-builder" />
	</objects>	

	<services>				
		<service name="log-service" class="com.warework.service.log.LogServiceImpl" />									
	</services>	
	
	<context>
		<scope name="system-c1">		
			<parameters>
				<parameter name="name" value="david"/>
				<parameter name="color" value="yellow"/>					
			</parameters>		
		</scope>
		<scope name="system-c2">		
			<parameters>
				<parameter name="name" value="rita"/>
				<parameter name="color" value="cyan"/>					
			</parameters>		
		</scope>		
	</context>
			
</scope>

=== warework/sdk-java/warework-java-mod-core-ext/src/test/resources/META-INF/warework-java-mod-core-ext/system-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<scope name="system-1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/scope.xsd">
	
	<providers>	
		
		<provider name="filetext-provider" class="com.warework.provider.FileTextProvider">
			<parameter name="file-extension" value="txt" />
			<parameter name="config-target" value="/META-INF/warework-java-mod-core-ext/txt" />
		</provider>	
		
		<provider name="properties-provider" class="com.warework.provider.PropertiesProvider">
			<parameter name="file-extension" value="txt" />
			<parameter name="config-target" value="/META-INF/warework-java-mod-core-ext/properties/sample-1.properties" />
		</provider>			
		
	</providers>

	<services>
		<service name="log-service" class="com.warework.service.log.LogServiceImpl" >
			<parameter name="config-class" value="com.warework.loader.ProxyServiceXmlLoader"/>			
			<parameter name="config-target" value="/META-INF/warework-java-mod-core-ext/log-service-1.xml"/>
		</service>									
	</services>	
			
</scope>

=== warework/sdk-java/warework-java-mod-core-ext/src/test/resources/META-INF/warework-java-mod-core-ext/system-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<scope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/scope.xsd">

	<parameters>
		<parameter name="context-loader" value="com.warework.loader.ProxyServiceXmlLoaderTest"/>
	</parameters>	

	<services>				
			
		<service name="log-service-1" class="com.warework.service.log.LogServiceImpl" >
			<parameter name="config-class" value="com.warework.loader.ProxyServiceXmlLoader"/>			
			<parameter name="config-target" value="/META-INF/warework-java-mod-core-ext/log-service-1.xml"/>
		</service>
		
		<service name="log-service-2" class="com.warework.service.log.LogServiceImpl" >			
			<parameter name="context-loader" value="com.warework.loader.ProxyServiceXmlLoaderTest"/>
			<parameter name="config-class" value="com.warework.loader.ProxyServiceXmlLoader"/>			
			<parameter name="config-target" value="/META-INF/warework-java-mod-core-ext/log-service-1.xml"/>
		</service>		
											
	</services>	
	
</scope>
